Repository bigbangcore/BigBang, pull requests merged in 2019-11, with the labels that each got.

#217 Make improvement for GetBlocksLocator
  src/bigbang/base.h
  src/bigbang/netchn.cpp
  src/bigbang/netchn.h
  src/bigbang/worldline.cpp
  src/bigbang/worldline.h
  src/storage/blockbase.cpp
  src/storage/blockbase.h
Labels: bug

#221 Rpc message
  script/template/options.json
  src/bigbang/base.h
  src/bigbang/entry.cpp
  src/bigbang/mode/basic_config.cpp
  src/bigbang/mode/config_macro.h
  src/bigbang/mode/rpc_config.cpp
  src/bigbang/netchn.cpp
  src/bigbang/rpcmod.cpp
  src/bigbang/rpcmod.h
  src/bigbang/service.cpp
  src/bigbang/service.h
  src/bigbang/worldline.cpp
  src/common/message.h
  src/xengine/CMakeLists.txt
  src/xengine/http/httpmessage.h
  src/xengine/http/httpserver.cpp
  src/xengine/http/httpserver.h
  src/xengine/nonce.h
  src/xengine/peernet/peernet.cpp
  src/xengine/util.h
  src/xengine/xengine.h
Labels: Performance, enhancement

#222 Wallet handle messages: added block, added tx, sync tx change
  script/template/options.json
  src/bigbang/base.h
  src/bigbang/dispatcher.cpp
  src/bigbang/entry.cpp
  src/bigbang/mode/config_macro.h
  src/bigbang/mode/mode.h
  src/bigbang/mode/module_type.h
  src/bigbang/mode/rpc_config.cpp
  src/bigbang/rpcmod.cpp
  src/bigbang/rpcmod.h
  src/bigbang/service.cpp
  src/bigbang/txpool/txpool.cpp
  src/bigbang/txpool/txpoolcontroller.cpp
  src/bigbang/wallet.cpp
  src/bigbang/wallet.h
  src/xengine/actor/actorworker.cpp
Labels: enhancement

#223 Add service controller
  src/bigbang/base.h
  src/bigbang/dispatcher.cpp
  src/bigbang/entry.cpp
  src/bigbang/netchn.cpp
  src/bigbang/netchn.h
  src/bigbang/service.cpp
  src/bigbang/service.h
  src/bigbang/txpool/txpoolcontroller.cpp
  src/bigbang/wallet.cpp
  src/common/message.h
  src/common/struct.h
Labels: enhancement

#225 Add consensus controller.
  src/bigbang/base.h
  src/bigbang/consensus.cpp
  src/bigbang/consensus.h
  src/bigbang/dispatcher.cpp
  src/bigbang/entry.cpp
  src/bigbang/netchn.cpp
  src/bigbang/param.h
  src/bigbang/rpcmod.cpp
  src/bigbang/service.cpp
  src/bigbang/txpool/txpoolcontroller.cpp
  src/bigbang/wallet.cpp
  src/bigbang/worldline.cpp
  src/common/message.h
Labels: enhancement

#227 Fix locator scheme
  src/bigbang/netchn.cpp
  src/bigbang/netchn.h
  src/storage/blockbase.cpp
Labels: improvement

#230 Fix address pool attack
  src/bigbang/network.cpp
  src/bigbang/network.h
  src/network/peer.cpp
  src/network/peer.h
  src/network/peernet.cpp
  src/network/peernet.h
Labels: security

#231 GetWork Service API support blockHashPrev parammeter
  src/bigbang/base.h
  src/bigbang/miner.cpp
  src/bigbang/miner.h
  src/bigbang/rpcmod.cpp
  src/bigbang/service.cpp
  src/bigbang/service.h
Labels: enhancement

#234 Remove explicit dispatcher in service
  src/bigbang/service.cpp
  src/bigbang/service.h
Labels: improvement

#237 Improve getwork rpc
  src/bigbang/base.h
  src/bigbang/rpcmod.cpp
  src/bigbang/service.cpp
  src/bigbang/service.h
Labels: improvement

#238 Revert typo when add JSON depth
  src/jsonrpc/json/json_spirit_reader_template.h
Labels: bug

#241 RPC unlockkey default unlocked time change from 0 to 60s with release mode
  src/bigbang/rpcmod.cpp
Labels: security

#243 Rpcclient error message
  src/bigbang/rpcclient.cpp
  src/xengine/docker/config.cpp
Labels: bug

#246 Ignore unrecognised option in configuration file
  src/xengine/docker/config.cpp
Labels: bug

#245 Remove Dispatcher in delegated channel
  src/bigbang/delegatedchn.cpp
  src/bigbang/delegatedchn.h
Labels: improvement

#252 Remove Dispatcher in BlockMaker
  src/bigbang/blockmaker.cpp
  src/bigbang/blockmaker.h
  src/bigbang/dispatcher.cpp
  src/bigbang/netchn.cpp
  src/bigbang/service.cpp
  src/bigbang/worldline.cpp
  src/bigbang/worldline.h
  src/common/message.h
Labels: improvement

#254 Add SyncForkHeight and PrimaryUpdate for delegatedchannel
  src/bigbang/consensus.cpp
  src/bigbang/delegatedchn.cpp
  src/bigbang/delegatedchn.h
  src/bigbang/dispatcher.cpp
  src/bigbang/worldline.cpp
  src/bigbang/worldline.h
Labels: improvement

#257 Add Send Delegate Tx when consensus UpdatePrimary
  src/bigbang/consensus.cpp
Labels: bug

#260 Remove all of calling Dispatcher explicitly
  src/bigbang/entry.cpp
  src/bigbang/mode/mode.h
  test/network_tests.cpp
Labels: improvement

#269 Check transaction type is valid or not
  src/bigbang/core.cpp
Labels: security

#271 Fix verify block Code completeness, and add an error "ERR_BLOCK_TYPE_INVALID"
  src/bigbang/blockchain.cpp
  src/bigbang/error.cpp
  src/bigbang/error.h
Labels: security

#266 fix bug: node with being connected mining machines cannot restart on …
  src/bigbang/blockmaker.cpp
  src/bigbang/blockmaker.h
  src/bigbang/service.cpp
Labels: bug

#276 Change unlock key default timeout from 10s to 60s when running without "-debug"
  src/bigbang/rpcmod.cpp
Labels: bug

#279 Actor message model
  src/bigbang/base.h
  src/bigbang/blockmaker.cpp
  src/bigbang/blockmaker.h
  src/bigbang/consensus.cpp
  src/bigbang/consensus.h
  src/bigbang/delegatedchn.cpp
  src/bigbang/delegatedchn.h
  src/bigbang/dispatcher.cpp
  src/bigbang/netchn.cpp
  src/bigbang/netchn.h
  src/bigbang/rpcmod.cpp
  src/bigbang/rpcmod.h
  src/bigbang/service.cpp
  src/bigbang/service.h
  src/bigbang/txpool/txpool.cpp
  src/bigbang/txpool/txpoolcontroller.cpp
  src/bigbang/txpool/txpoolcontroller.h
  src/bigbang/wallet.cpp
  src/bigbang/wallet.h
  src/bigbang/worldline.cpp
  src/common/message.h
  src/common/struct.h
  src/network/peernet.cpp
  src/network/peernet.h
  src/xengine/CMakeLists.txt
  src/xengine/actor/actor.cpp
  src/xengine/actor/actor.h
  src/xengine/actor/actorworker.cpp
  src/xengine/actor/actorworker.h
  src/xengine/actor/workermanager.h
  src/xengine/docker/docker.cpp
  src/xengine/docker/thread.h
  src/xengine/docker/timer.cpp
  src/xengine/docker/timer.h
  src/xengine/http/httpmessage.h
  src/xengine/http/httpserver.cpp
  src/xengine/http/httpserver.h
  src/xengine/logger.h
  src/xengine/message/macro.h
  src/xengine/message/message.h
  src/xengine/message/messagecenter.cpp
  src/xengine/message/messagecenter.h
  src/xengine/netio/ioproc.cpp
  src/xengine/netio/ioproc.h
  src/xengine/nonce.h
  src/xengine/peernet/message.h
  src/xengine/peernet/peernet.cpp
  src/xengine/peernet/peernet.h
  src/xengine/util.h
  test/actor_tests.cpp
  test/network_tests.cpp
  test/timer_tests.cpp
Labels: enhancement

#281 Optimize RPC listunspent
  script/auto_protocol.py
  script/template/rpc.json
  src/bigbang/base.h
  src/bigbang/blockchain.cpp
  src/bigbang/blockchain.h
  src/bigbang/rpcmod.cpp
  src/bigbang/service.cpp
  src/bigbang/service.h
  src/bigbang/wallet.cpp
  src/bigbang/wallet.h
  src/storage/blockbase.cpp
  src/storage/blockbase.h
  src/storage/unspentdb.h
Labels: enhancement

#282 Add rpc importpubkey
  script/auto_protocol.py
  script/auto_rpc.py
  script/generator.py
  script/template/rpc.json
  src/bigbang/CMakeLists.txt
  src/bigbang/base.h
  src/bigbang/config.cpp
  src/bigbang/miner.cpp
  src/bigbang/rpcclient.cpp
  src/bigbang/rpcmod.cpp
  src/bigbang/rpcmod.h
  src/bigbang/service.cpp
  src/bigbang/service.h
  src/bigbang/wallet.cpp
  src/bigbang/wallet.h
  src/crypto/crypto.h
  src/crypto/key.cpp
  src/crypto/key.h
Labels: enhancement

#290 Automatically delay lock time when signing with private key
  src/bigbang/base.h
  src/bigbang/wallet.cpp
  src/bigbang/wallet.h
Labels: enhancement

#296 Don't allow TX_CERT transaction and non-primary block
  src/bigbang/core.cpp
Labels: security

#298 Fix wallet sequence bug
  src/storage/walletdb.cpp
  src/xengine/util.h
Labels: bug

#306 Fix RPC block time of getwork
  src/bigbang/service.cpp
Labels: bug
