Repository bigbangcore/BigBang, pull requests merged in 2019-12, with the labels that each got.

#316 Fix start failed in new way
  src/bigbang/rpcmod.cpp
  src/crypto/crypto.cpp
  src/crypto/crypto.h
Labels: bug

#317 Fix UAF bug
  src/xengine/netio/iocontainer.cpp
  src/xengine/netio/iocontainer.h
  src/xengine/peernet/peer.cpp
  src/xengine/peernet/peer.h
  src/xengine/peernet/peernet.cpp
  src/xengine/peernet/peernet.h
Labels: bug, security

#332 Fix DVP leak: bad length vector of stream.
  src/common/proof.h
  src/common/template/exchange.cpp
  src/common/template/exchange.h
  src/crypto/key.cpp
  src/xengine/stream/stream.h
Labels: security

#327 Fix get mintx failed when program crash or be killed
  src/storage/blockdb.cpp
  src/storage/txindexdb.cpp
  src/storage/txindexdb.h
  src/storage/unspentdb.cpp
  src/storage/unspentdb.h
Labels: bug

#348 Avoid Boost v1.71 linking error
  CMakeLists.txt
Labels: building-problem

#347 Remove the special map struct of weighted and multisign template
  src/common/template/multisig.cpp
  src/common/template/multisig.h
  src/common/template/weighted.cpp
  src/common/template/weighted.h
Labels: bug

#349 Judgement of multisig nRequired bug
  src/common/template/multisig.cpp
Labels: bug

#353 Fix JSON depth bug
  script/auto_protocol.py
  src/bigbang/rpcmod.cpp
Labels: security

#354 Check vector size of CProofOfHashWorkCompact functions for defensive programming
  src/common/proof.h
Labels: security
