Repository bigbangcore/BigBang, pull requests merged in 2019-09, with the labels that each got.

#63 log file contains date
  src/xengine/util.cpp
  test/test_big_main.cpp
Labels: enhancement

#61 Improve uint256
  src/crypto/uint256.h
  test/uint256_tests.cpp
Labels: enhancement

#65 Map to unordered map
  src/bigbang/consensus.cpp
  src/bigbang/struct.h
  src/bigbang/txpool.cpp
  src/bigbang/txpool.h
  src/bigbang/wallet.cpp
  src/storage/blockbase.cpp
  src/storage/blockbase.h
  test/uint256_tests.cpp
Labels: Performance

#67 Change push_back to emplace_back and simplify statement
  src/bigbang/consensus.cpp
  src/bigbang/netchn.h
  src/bigbang/schedule.cpp
  src/bigbang/schedule.h
  src/bigbang/txpool.cpp
  src/bigbang/txpool.h
  src/bigbang/wallet.cpp
  src/leveldb/db/version_edit.h
  src/mpvss/mpinterpolation.cpp
  src/mpvss/mpvss.cpp
  src/network/peerevent.h
  src/storage/blockbase.cpp
  src/storage/unspentdb.h
  src/storage/walletdb.h
  src/xengine/cache.h
Labels: Performance

#70 Add Message center
  src/xengine/CMakeLists.txt
  src/xengine/message/actor.cpp
  src/xengine/message/actor.h
  src/xengine/message/message.h
  src/xengine/message/messagecenter.cpp
  src/xengine/message/messagecenter.h
  test/CMakeLists.txt
  test/actor_tests.cpp
Labels: enhancement

#73 Fix path of log file in real-time
  src/xengine/util.cpp
Labels: enhancement

#74 Fix bug of std::bad_alloc
  src/storage/blockbase.cpp
Labels: bug

#77 Reduce one hash operation
  src/crypto/uint256.h
Labels: enhancement

#79 Improve log
  src/bigbang/bigbang.cpp
  src/bigbang/config.cpp
  src/bigbang/datastat.cpp
  src/bigbang/entry.cpp
  src/bigbang/miner.cpp
  src/bigbang/rpcclient.cpp
  src/bigbang/service.cpp
  src/common/profile.cpp
  src/common/template/delegate.cpp
  src/common/template/exchange.cpp
  src/common/template/fork.cpp
  src/common/template/proof.cpp
  src/common/template/template.h
  src/common/template/weighted.cpp
  src/crypto/key.cpp
  src/delegate/delegate.cpp
  src/delegate/delegateverify.cpp
  src/delegate/delegatevote.cpp
  src/mpvss/mpbox.cpp
  src/mpvss/mpvss.cpp
  src/mpvss/parallel.h
  src/network/peer.cpp
  src/network/peerevent.h
  src/storage/blockbase.cpp
  src/storage/purger.cpp
  src/storage/timeseries.cpp
  src/storage/timeseries.h
  src/storage/txpooldata.cpp
  src/storage/unspentdb.cpp
  src/xengine/CMakeLists.txt
  src/xengine/console/console.cpp
  src/xengine/db/kvdb.h
  src/xengine/docker/config.cpp
  src/xengine/docker/log.h
  src/xengine/event/event.h
  src/xengine/http/httpsse.h
  src/xengine/http/httputil.cpp
  src/xengine/logger.cpp
  src/xengine/logger.h
  src/xengine/netio/ioclient.cpp
  src/xengine/netio/iocontainer.cpp
  src/xengine/netio/ioproc.cpp
  src/xengine/util.cpp
  src/xengine/util.h
Labels: enhancement

#80 Msg queue center
  src/xengine/CMakeLists.txt
  src/xengine/lockfree/queue.h
  src/xengine/message/actor.h
  src/xengine/message/message.h
  src/xengine/message/messagecenter.cpp
  src/xengine/message/messagecenter.h
  test/actor_tests.cpp
Labels: enhancement

#81 Add IModel and IController
  src/xengine/CMakeLists.txt
  src/xengine/base/controller.h
  src/xengine/base/model.h
  src/xengine/message/actor.cpp
  src/xengine/message/actor.h
Labels: enhancement

#82 Add a string tag variable to CMessage
  src/xengine/message/message.h
  src/xengine/message/messagecenter.cpp
  test/actor_tests.cpp
Labels: enhancement

#90 Fix the crashing of httpserver when stop. Add StopService in LeaveLoop()
  src/xengine/http/httpserver.cpp
  src/xengine/netio/ioproc.cpp
Labels: bug

#92 Change PostEvent to NetChannel from Event to Message Model
  src/bigbang/dispatcher.h
  src/bigbang/netchn.cpp
  src/bigbang/netchn.h
  src/common/CMakeLists.txt
  src/common/message.cpp
  src/common/message.h
  src/network/CMakeLists.txt
  src/network/peernet.cpp
  src/network/peernet.h
Labels: enhancement

#94 Add publishing shared_ptr<message> function in CMessageCenter
  src/xengine/lockfree/queue.h
  src/xengine/message/messagecenter.cpp
  src/xengine/message/messagecenter.h
  test/actor_tests.cpp
Labels: enhancement

#96 Add timer actor module: xengine::CTimer
  src/xengine/CMakeLists.txt
  src/xengine/docker/docker.cpp
  src/xengine/docker/docker.h
  src/xengine/docker/timer.cpp
  src/xengine/docker/timer.h
  src/xengine/docker/timertask.h
  src/xengine/message/actor.h
  src/xengine/xengine.h
  test/CMakeLists.txt
  test/timer_tests.cpp
Labels: enhancement

#97 Non functional modification
  .clang-format
  src/bigbang/base.h
  src/bigbang/blockchain.cpp
  src/bigbang/datastat.cpp
  src/bigbang/dispatcher.cpp
  src/bigbang/rpcmod.cpp
  src/bigbang/struct.h
  src/common/template/template.h
  src/delegate/delegate.cpp
  src/jsonrpc/json/json_spirit_reader_template.h
  src/leveldb/include/leveldb/cache.h
  src/leveldb/include/leveldb/db.h
  src/leveldb/include/leveldb/env.h
  src/network/peernet.h
  src/storage/blockbase.h
  src/xengine/http/httpsse.h
  src/xengine/netio/ioclient.cpp
  src/xengine/netio/iocontainer.cpp
  test/actor_tests.cpp
Labels: code-style

#98 Change DispatchEvent to PeerNet from Event to Message Model
  src/bigbang/netchn.cpp
  src/bigbang/netchn.h
  src/common/message.cpp
  src/common/message.h
  src/network/peernet.cpp
  src/network/peernet.h
  src/xengine/CMakeLists.txt
  src/xengine/peernet/message.cpp
  src/xengine/peernet/message.h
  src/xengine/peernet/peernet.cpp
  src/xengine/peernet/peernet.h
Labels: enhancement

#100 Remove Relative include path
  src/bigbang/core.cpp
  src/bigbang/wallet.cpp
  src/common/CMakeLists.txt
  src/common/message.h
  src/common/template/exchange.cpp
  src/network/CMakeLists.txt
  src/xengine/stream/stream.h
Labels: enhancement

#101 Enhance macros about CMessage derived class.
  src/common/CMakeLists.txt
  src/common/message.cpp
  src/common/message.h
  src/xengine/CMakeLists.txt
  src/xengine/docker/timer.cpp
  src/xengine/docker/timer.h
  src/xengine/message/actor.h
  src/xengine/message/message.h
  src/xengine/message/messagecenter.cpp
  src/xengine/peernet/message.cpp
  src/xengine/peernet/message.h
  test/actor_tests.cpp
  test/timer_tests.cpp
Labels: enhancement

#102 Remove common's dependence on bigbang
  src/common/CMakeLists.txt
  src/common/template/exchange.cpp
  src/xengine/message/message.h
Labels: enhancement

#103 Change CTxPool inheritance relationship to CIOActor
  src/bigbang/CMakeLists.txt
  src/bigbang/base.h
  src/bigbang/netchn.cpp
  src/bigbang/txpool.cpp
  src/bigbang/txpool.h
  src/common/CMakeLists.txt
  src/common/message.h
  src/common/struct.h
  src/xengine/xengine.h
Labels: enhancement

#112 Check return value of make command on MacOS
  INSTALL.sh
Labels: bug

#113 Check return value of make command on MacOS
  INSTALL.sh
Labels: bug

#104 Add Netchannel unit test
  src/bigbang/CMakeLists.txt
  src/bigbang/blockchain.cpp
  src/bigbang/blockmaker.cpp
  src/bigbang/consensus.cpp
  src/bigbang/datastat.cpp
  src/bigbang/forkmanager.cpp
  src/bigbang/netchn.cpp
  src/bigbang/wallet.cpp
  src/network/peernet.cpp
  test/CMakeLists.txt
  test/netchn_tests.cpp
  test/test_big.cpp
  test/test_big.h
Labels: enhancement

#116 Refactor CMakeLists.txt
  src/bigbang/CMakeLists.txt
Labels: code-style

#120 Extend limitation time in timer_tests.
  test/timer_tests.cpp
Labels: Robustness

#121 Impl StdLog to support Variable Arguments
  src/xengine/logger.h
Labels: enhancement

#119 Change delegatedchannel and peernet to message model
  src/bigbang/delegatedchn.cpp
  src/bigbang/delegatedchn.h
  src/bigbang/dispatcher.h
  src/bigbang/netchn.cpp
  src/bigbang/network.cpp
  src/common/message.h
  src/network/peernet.cpp
  src/network/peernet.h
  src/xengine/docker/docker.cpp
  src/xengine/peernet/peernet.cpp
  test/netchn_tests.cpp
Labels: enhancement

#129 Split a bunch of sources out to libbigbang
  src/bigbang/CMakeLists.txt
Labels: building-problem

#126 Set out of source datadir for unit test
  .gitignore
  test/netchn_tests.cpp
Labels: enhancement

#131 Optimize actor handler message parameter from `const shared_ptr<T>` to `const shared_ptr<T>&`
  src/xengine/message/actor.h
  src/xengine/message/actorworker.h
  src/xengine/message/message.h
  test/actor_tests.cpp
Labels: enhancement
