Repository bigbangcore/BigBang, pull requests merged in 2019-08, with the labels that each got.

#4 Fix CI build failed
  .travis.yml
  CMakeLists.txt
  INSTALL.sh
  src/bigbang/datastat.cpp
  src/bigbang/delegatedchn.cpp
  src/bigbang/miner.cpp
  src/bigbang/rpcclient.cpp
  src/bigbang/rpcmod.cpp
  src/bigbang/rpcmod.h
  src/bigbang/service.cpp
  src/bigbang/struct.h
  src/bigbang/txpool.cpp
  src/bigbang/txpool.h
  src/common/transaction.h
  src/storage/leveldbeng.cpp
  src/xengine/http/httpserver.cpp
  src/xengine/http/httpserver.h
  src/xengine/http/httpsse.h
  src/xengine/peernet/epmngr.cpp
  src/xengine/peernet/peer.cpp
  src/xengine/peernet/peernet.cpp
  test/CMakeLists.txt
  test/mpvss_tests.cpp
Labels: bug

#15 Add exclude dir script and test in cppcheck
  .travis.yml
Labels: enhancement

#17 Remove -O3 flag
  CMakeLists.txt
Labels: bug

#19 Replace NULL by nullptr
  src/bigbang/blockchain.cpp
  src/bigbang/blockmaker.cpp
  src/bigbang/blockmaker.h
  src/bigbang/config.cpp
  src/bigbang/consensus.cpp
  src/bigbang/core.cpp
  src/bigbang/datastat.cpp
  src/bigbang/delegatedchn.cpp
  src/bigbang/dispatcher.cpp
  src/bigbang/entry.cpp
  src/bigbang/forkmanager.cpp
  src/bigbang/miner.cpp
  src/bigbang/mode/basic_config.h
  src/bigbang/mode/config_type.h
  src/bigbang/mode/mode.h
  src/bigbang/netchn.cpp
  src/bigbang/rpcclient.cpp
  src/bigbang/rpcmod.cpp
  src/bigbang/schedule.cpp
  src/bigbang/service.cpp
  src/bigbang/txpool.cpp
  src/bigbang/txpool.h
  src/bigbang/wallet.cpp
  src/bigbang/wallet.h
  src/common/block.h
  src/common/template/template.cpp
  src/common/wallettx.h
  src/crypto/crypto.cpp
  src/jsonrpc/rpc/rpc_req.h
  src/jsonrpc/rpc/rpc_resp.h
  src/network/peernet.cpp
  src/storage/blockbase.cpp
  src/storage/blockbase.h
  src/storage/leveldbeng.cpp
  src/storage/timeseries.cpp
  src/storage/txindexdb.cpp
  src/storage/txpooldata.cpp
  src/storage/unspentdb.cpp
  src/xengine/base/base.cpp
  src/xengine/base/base.h
  src/xengine/console/console.cpp
  src/xengine/db/kvdb.h
  src/xengine/docker/docker.cpp
  src/xengine/docker/docker.h
  src/xengine/docker/log.h
  src/xengine/docker/thread.h
  src/xengine/event/eventproc.cpp
  src/xengine/event/eventproc.h
  src/xengine/http/httpcookie.cpp
  src/xengine/http/httpget.cpp
  src/xengine/http/httpserver.cpp
  src/xengine/http/httpserver.h
  src/xengine/http/httputil.cpp
  src/xengine/netio/iocontainer.cpp
  src/xengine/netio/nethost.cpp
  src/xengine/peernet/datasched.h
  src/xengine/peernet/peernet.cpp
  src/xengine/peernet/peernet.h
  src/xengine/util.cpp
Labels: enhancement

#20 Update README.md
  README.md
Labels: documentation

#23 bug fix for failing to pass the build process for debug configuration on MacOS
  CMakeLists.txt
Labels: buiding-problem

#25 Add coding style guides link
  README.md
Labels: documentation

#26 Fix the linking warning caused by boost libraries visibility on macos
  CMakeLists.txt
Labels: buiding-problem

#24 Add .gitattributes
  .gitattributes
Labels: enhancement

#28 Boost log
  CMakeLists.txt
  src/bigbang/entry.cpp
  src/xengine/CMakeLists.txt
  src/xengine/docker/log.h
  src/xengine/util.cpp
  src/xengine/util.h
Labels: enhancement

#29 Use dependencies as static lib
  .travis.yml
  CMakeLists.txt
  cmake/FindProtobuf.cmake
  cmake/FindReadline.cmake
  src/bigbang/CMakeLists.txt
  src/common/CMakeLists.txt
  src/crypto/CMakeLists.txt
  src/delegate/CMakeLists.txt
  src/jsonrpc/CMakeLists.txt
  src/network/CMakeLists.txt
  src/storage/CMakeLists.txt
  src/xengine/CMakeLists.txt
  test/CMakeLists.txt
Labels: enhancement

#35 Support boost 1.58
  src/bigbang/entry.cpp
  src/snappy/testdata/alice29.txt
  src/snappy/testdata/lcet10.txt
  src/snappy/testdata/plrabn12.txt
  src/xengine/util.cpp
  src/xengine/util.h
  test/exchange.sh
  tools/exchange/createForkAndExchange.sh
  tools/exchange/exchange.md
  tools/exchange/script.txt
Labels: enhancement
