Repository bigbangcore/BigBang, pull requests merged in 2019-10, with the labels that each got.

#132 Refactor ipv6 test
  test/CMakeLists.txt
  test/ip_tests.cpp
  test/ipv6_tests.cpp
Labels: Robustness

#134 Change CPeerNet from event to message model
  src/common/message.h
  src/xengine/peernet/message.h
  src/xengine/peernet/peernet.cpp
  src/xengine/peernet/peernet.h
  test/CMakeLists.txt
  test/network_tests.cpp
Labels: enhancement

#139 Modify CTxPool to actor model
  src/bigbang/base.h
  src/bigbang/blockchain.cpp
  src/bigbang/blockchain.h
  src/bigbang/blockmaker.cpp
  src/bigbang/blockmaker.h
  src/bigbang/consensus.cpp
  src/bigbang/consensus.h
  src/bigbang/dispatcher.cpp
  src/bigbang/dispatcher.h
  src/bigbang/entry.cpp
  src/bigbang/mode/mode.h
  src/bigbang/mode/module_type.h
  src/bigbang/netchn.cpp
  src/bigbang/netchn.h
  src/bigbang/service.cpp
  src/bigbang/service.h
  src/bigbang/txpool.cpp
  src/bigbang/txpool.h
  src/bigbang/wallet.cpp
  src/bigbang/wallet.h
  src/common/message.h
  test/network_tests.cpp
Labels: enhancement

#140 Remove DispatchEvent in CService
  src/bigbang/base.h
  src/bigbang/delegatedchn.cpp
  src/bigbang/delegatedchn.h
  src/bigbang/dispatcher.h
  src/bigbang/netchn.cpp
  src/bigbang/netchn.h
  src/bigbang/service.cpp
  src/bigbang/service.h
  src/network/peernet.h
Labels: enhancement

#141 IWallet extends CIOActor
  src/bigbang/base.h
Labels: enhancement

#142 IConsensus extends CIOActor
  src/bigbang/base.h
Labels: enhancement

#144 Worldline message
  script/create_json_rpc_wiki.py
  src/bigbang/CMakeLists.txt
  src/bigbang/base.h
  src/bigbang/blockmaker.cpp
  src/bigbang/blockmaker.h
  src/bigbang/consensus.cpp
  src/bigbang/consensus.h
  src/bigbang/delegatedchn.cpp
  src/bigbang/delegatedchn.h
  src/bigbang/dispatcher.cpp
  src/bigbang/dispatcher.h
  src/bigbang/entry.cpp
  src/bigbang/forkmanager.cpp
  src/bigbang/forkmanager.h
  src/bigbang/mode/mode.h
  src/bigbang/mode/module_type.h
  src/bigbang/netchn.cpp
  src/bigbang/netchn.h
  src/bigbang/rpcmod.cpp
  src/bigbang/service.cpp
  src/bigbang/service.h
  src/bigbang/txpool.cpp
  src/bigbang/txpool.h
  src/bigbang/wallet.cpp
  src/bigbang/wallet.h
  src/bigbang/worldline.cpp
  src/bigbang/worldline.h
  src/common/message.h
  src/common/struct.h
  src/xengine/cache.h
  src/xengine/docker/timer.cpp
  src/xengine/docker/timer.h
  src/xengine/message/actor.cpp
  src/xengine/message/actor.h
  src/xengine/message/messagecenter.cpp
  src/xengine/netio/ioproc.cpp
  test/actor_tests.cpp
  test/network_tests.cpp
  test/test_big.cpp
  test/test_big.h
  test/timer_tests.cpp
Labels: enhancement

#146 Enhance the function AddTx and RemoveTx of CBlockView to check tx is valid or not
  src/bigbang/worldline.cpp
  src/storage/blockbase.cpp
  src/storage/blockbase.h
Labels: enhancement

#145 Lock-free queue push rvalue pointer
  src/bigbang/worldline.cpp
  src/xengine/lockfree/queue.h
  src/xengine/message/messagecenter.cpp
  src/xengine/message/messagecenter.h
  test/actor_tests.cpp
  test/network_tests.cpp
Labels: bug

#147 Replace INetChannelController API to Message Model
  src/bigbang/delegatedchn.cpp
  src/bigbang/dispatcher.cpp
  src/bigbang/dispatcher.h
  src/bigbang/netchn.cpp
  src/bigbang/netchn.h
  src/bigbang/worldline.cpp
  src/common/message.h
  src/network/peernet.cpp
  src/network/peernet.h
  src/xengine/base/model.h
  test/network_tests.cpp
Labels: enhancement

#152 Fix the launching parameter and dynamic difficulty bug of miner mode
  src/bigbang/config.cpp
  src/bigbang/miner.cpp
  src/bigbang/miner.h
  src/bigbang/mode/mode.h
Labels: bug

#153 Fix typo
  script/auto_options.py
  script/auto_protocol.py
  script/auto_rpc.py
  script/create_json_rpc_wiki.py
  script/generator.py
  script/tool.py
  src/bigbang/base.h
  src/bigbang/blockmaker.cpp
  src/bigbang/blockmaker.h
  src/bigbang/consensus.cpp
  src/bigbang/consensus.h
  src/bigbang/delegatedchn.cpp
  src/bigbang/delegatedchn.h
  src/bigbang/dispatcher.cpp
  src/bigbang/dispatcher.h
  src/bigbang/entry.cpp
  src/bigbang/forkmanager.cpp
  src/bigbang/forkmanager.h
  src/bigbang/mode/module_type.h
  src/bigbang/netchn.cpp
  src/bigbang/netchn.h
  src/bigbang/service.cpp
  src/bigbang/service.h
  src/bigbang/txpool.cpp
  src/bigbang/txpool.h
  src/bigbang/wallet.cpp
  src/bigbang/wallet.h
  src/bigbang/worldline.cpp
  src/bigbang/worldline.h
  src/common/template/exchange.cpp
  src/xengine/base/model.h
  src/xengine/message/actor.h
  src/xengine/message/message.h
  src/xengine/message/messagecenter.cpp
  test/network_tests.cpp
Labels: code-style

#155 Blockmaker message
  src/bigbang/base.h
  src/bigbang/blockmaker.cpp
  src/bigbang/blockmaker.h
  src/bigbang/consensus.cpp
  src/bigbang/delegatedchn.cpp
  src/bigbang/dispatcher.cpp
  src/bigbang/entry.cpp
  src/bigbang/mode/module_type.h
  src/bigbang/netchn.cpp
  src/bigbang/netchn.h
  src/bigbang/service.cpp
  src/bigbang/txpool.cpp
  src/bigbang/txpool.h
  src/bigbang/wallet.cpp
  src/bigbang/worldline.cpp
  src/bigbang/worldline.h
  src/xengine/base/model.h
  src/xengine/netio/ioproc.cpp
  test/network_tests.cpp
Labels: enhancement

#166 Split txpool classes into different files, and fix adding new block problem.
  src/bigbang/CMakeLists.txt
  src/bigbang/base.h
  src/bigbang/dispatcher.cpp
  src/bigbang/entry.cpp
  src/bigbang/txpool.h
  src/bigbang/txpool/txpool.cpp
  src/bigbang/txpool/txpool.h
  src/bigbang/txpool/txpoolcontroller.cpp
  src/bigbang/txpool/txpoolcontroller.h
  src/bigbang/txpool/txpoolview.cpp
  src/bigbang/txpool/txpoolview.h
  src/bigbang/txpool/txset.h
  src/bigbang/worldline.cpp
  src/bigbang/worldline.h
  test/network_tests.cpp
Labels: bug, enhancement

#171 Trace format log
  src/xengine/util.cpp
  src/xengine/util.h
Labels: enhancement

#176 Remove dynamic change of PoW difficulty
  src/bigbang/base.h
  src/bigbang/blockmaker.cpp
  src/bigbang/core.cpp
  src/bigbang/core.h
  src/bigbang/miner.cpp
  src/bigbang/miner.h
Labels: security

#179 Fix the bug of launch parameter in miner mode
  src/bigbang/config.cpp
  src/bigbang/miner.cpp
Labels: bug

#180 Remove additional dpos code
  src/bigbang/blockchain.cpp
Labels: enhancement

#182 Db blockmaker txpool trace log
  src/bigbang/blockmaker.cpp
  src/bigbang/txpool.cpp
  src/storage/blockbase.cpp
Labels: enhancement

#185 Modify chain weight rules
  src/bigbang/base.h
  src/bigbang/blockchain.cpp
  src/bigbang/blockchain.h
  src/bigbang/core.cpp
  src/bigbang/core.h
  src/common/block.h
  src/storage/blockbase.cpp
  src/storage/blockbase.h
Labels: enhancement

#169 Netchannel model
  src/bigbang/base.h
  src/bigbang/core.cpp
  src/bigbang/core.h
  src/bigbang/dispatcher.cpp
  src/bigbang/dispatcher.h
  src/bigbang/entry.cpp
  src/bigbang/netchn.cpp
  src/bigbang/netchn.h
  src/bigbang/schedule.cpp
  src/bigbang/schedule.h
  src/network/peernet.h
  src/xengine/base/model.h
  test/network_tests.cpp
Labels: enhancement

#186 Add trace log for blockbase
  src/storage/blockbase.cpp
Labels: enhancement

#187 Remove dispatcher dependency for netchannel
  src/bigbang/netchn.cpp
  src/bigbang/netchn.h
  src/xengine/message/actorworker.cpp
  test/timer_tests.cpp
Labels: improvement

#197 Add nHeight in CBlock, and previous 4 bytes of block hash is nHeight
  src/bigbang/blockmaker.cpp
  src/bigbang/core.cpp
  src/bigbang/error.h
  src/common/block.h
  src/storage/blockbase.cpp
Labels: enhancement

#196 Handle AddedTx already have error
  src/bigbang/netchn.cpp
Labels: bug

#201 Fix nLockutil of tx bug
  src/bigbang/core.cpp
  src/bigbang/error.cpp
  src/bigbang/service.cpp
  src/bigbang/txpool.cpp
Labels: bug

#202 Remove block structure parameter nHeight.
  src/bigbang/blockmaker.cpp
  src/bigbang/core.cpp
  src/bigbang/error.cpp
  src/bigbang/error.h
  src/bigbang/service.cpp
  src/common/block.h
Labels: bug

#208 Upgrade CHttpServer to message model
  src/bigbang/rpcmod.cpp
  src/bigbang/rpcmod.h
  src/xengine/CMakeLists.txt
  src/xengine/http/httpmessage.h
  src/xengine/http/httpserver.cpp
  src/xengine/http/httpserver.h
Labels: enhancement

#216 Little adjustment of actor
  src/network/peernet.h
  src/xengine/CMakeLists.txt
  src/xengine/actor/actor.cpp
  src/xengine/actor/actor.h
  src/xengine/actor/actorworker.cpp
  src/xengine/actor/actorworker.h
  src/xengine/docker/timer.cpp
  src/xengine/docker/timer.h
  src/xengine/http/httpserver.cpp
  src/xengine/http/httpserver.h
  src/xengine/message/messagecenter.cpp
  src/xengine/netio/ioproc.cpp
  src/xengine/netio/ioproc.h
  src/xengine/peernet/peernet.cpp
  src/xengine/peernet/peernet.h
  src/xengine/xengine.h
  test/actor_tests.cpp
  test/network_tests.cpp
  test/timer_tests.cpp
Labels: improvement

#219 Unify nonce
  src/bigbang/netchn.cpp
  src/bigbang/txpool/txpoolcontroller.cpp
  src/bigbang/worldline.cpp
  src/common/message.h
  src/xengine/http/httpserver.cpp
  src/xengine/peernet/peernet.cpp
  src/xengine/util.h
Labels: improvement
