Repository bigbangcore/BigBang, pull requests merged in 2020-01, with the labels that each got.

#352 Add checkpoints candidate tool written in Python
  tools/checkpoints.py
Labels: enhancement

#361 Fix RPC ExportWallet file path error in CYGWIN env
  CMakeLists.txt
  src/bigbang/rpcmod.cpp
Labels: bug

#357 Listunspent multi addr
  script/template/rpc.json
  src/bigbang/base.h
  src/bigbang/blockchain.cpp
  src/bigbang/blockchain.h
  src/bigbang/rpcclient.cpp
  src/bigbang/rpcmod.cpp
  src/bigbang/service.cpp
  src/bigbang/service.h
  src/bigbang/wallet.cpp
  src/storage/blockbase.cpp
  src/storage/blockbase.h
  src/storage/unspentdb.h
Labels: Performance, enhancement

#359 Enhance RPC: add more detailed error message
  src/bigbang/base.h
  src/bigbang/rpcmod.cpp
  src/bigbang/service.cpp
  src/bigbang/service.h
  src/bigbang/wallet.cpp
  src/bigbang/wallet.h
Labels: enhancement

#364 Enhance RPC Listtransaction
  script/template/rpc.json
  src/bigbang/base.h
  src/bigbang/rpcmod.cpp
  src/bigbang/service.cpp
  src/bigbang/service.h
  src/bigbang/wallet.cpp
  src/bigbang/wallet.h
  src/storage/walletdb.cpp
  src/storage/walletdb.h
Labels: enhancement
