Repository bigbangcore/BigBang, pull requests merged in 2020-06, with the labels that each got.

#550 Offline signtx for delegate addr owned by multisign addr
  script/template/rpc.json
  src/bigbang/base.h
  src/bigbang/core.cpp
  src/bigbang/entry.cpp
  src/bigbang/rpcmod.cpp
  src/bigbang/service.cpp
  src/bigbang/service.h
  src/bigbang/wallet.cpp
  src/bigbang/wallet.h
  src/common/defs.cpp
  src/common/defs.h
  src/common/template/template.h
  src/crypto/pow_hash/slow-hash.c
  src/crypto/pow_hash/slow-hash_1.c
Labels: enhancement

#557 Improve RPC ListUnspent feature
  src/bigbang/base.h
  src/bigbang/service.cpp
  src/bigbang/txpool.cpp
  src/bigbang/txpool.h
Labels: enhancement

#563 Update CheckPoint
  src/bigbang/blockchain.cpp
Labels: Robustness

#564 Fix check repair txpool bug
  src/bigbang/checkrepair.cpp
  src/bigbang/checkrepair.h
Labels: bug

#567 Add doc for test tools
  tools/test-tools.md
Labels: documentation

#569 Update Version
  CHANGELOG.md
  src/bigbang/version.h
Labels: documentation
