Repository bigbangcore/BigBang, pull requests merged in 2020-03, with the labels that each got.

#408 Dpos delegatechn and consensus rollback
  src/bigbang/base.h
  src/bigbang/consensus.cpp
  src/bigbang/consensus.h
  src/bigbang/delegatedchn.cpp
  src/bigbang/delegatedchn.h
  src/bigbang/dispatcher.cpp
  src/bigbang/dispatcher.h
  src/bigbang/struct.h
  src/delegate/delegate.cpp
  src/delegate/delegate.h
  src/delegate/delegatevote.h
  src/network/peerevent.h
  src/network/peernet.cpp
  src/network/peernet.h
  test/CMakeLists.txt
  test/delegate_tests.cpp
Labels: DPoS

#405 Add raw tx ops
  script/template/rpc.json
  src/bigbang/base.h
  src/bigbang/core.cpp
  src/bigbang/rpcmod.cpp
  src/bigbang/rpcmod.h
  src/bigbang/service.cpp
  src/bigbang/service.h
  src/bigbang/wallet.cpp
  src/common/destination.cpp
  src/common/template/template.cpp
  src/common/template/weighted.cpp
Labels: enhancement

#413 Fix Enroll tx first goes into Block
  .gitattributes
  .gitignore
  src/bigbang/blockmaker.cpp
  src/bigbang/txpool.cpp
  src/common/transaction.h
Labels: bug

#421 Change TxPool ArrangeBlockTx API
  src/bigbang/base.h
  src/bigbang/blockmaker.cpp
  src/bigbang/service.cpp
  src/bigbang/txpool.cpp
  src/bigbang/txpool.h
  test/CMakeLists.txt
  test/storage_tests.cpp
  test/txpool_tests.cpp
Labels: DPoS

#426 SendFrom need to reach mortgage tx amount at once for creating fork
  src/bigbang/rpcmod.cpp
  src/common/template/fork.cpp
Labels: improvement

#430 Improve ImportWallet path check on windows
  src/bigbang/rpcmod.cpp
Labels: improvement

#432 Improve build performance for prepare for libsodium source
  src/bigbang/CMakeLists.txt
Labels: building-problem, improvement

#444 Improve gettransaction response add Fix confirmations error
  script/template/rpc.json
  src/bigbang/rpcmod.cpp
Labels: bug

#446 fix txpool seq bug
  src/bigbang/txpool.cpp
  src/bigbang/txpool.h
  test/txpool_tests.cpp
Labels: bug
