Repository bigbangcore/BigBang, pull requests merged in 2020-07, with the labels that each got.

#570 Fix signature bug and add "sendtodata" option
  script/template/rpc.json
  src/bigbang/core.cpp
  src/bigbang/rpcmod.cpp
  src/bigbang/wallet.cpp
Labels: bug, enhancement

#571 Enhance verification of CERT
  src/bigbang/core.cpp
  src/bigbang/core.h
Labels: security

#577 fix crash when failing to inspect wallet tx
  src/bigbang/checkrepair.cpp
  src/storage/blockbase.cpp
Labels: bug

#578 Fix consensus bug: not check repeated publish
  src/bigbang/base.h
  src/bigbang/blockchain.cpp
  src/bigbang/checkrepair.cpp
  src/bigbang/core.cpp
  src/bigbang/core.h
  src/delegate/delegateverify.cpp
  src/delegate/delegateverify.h
  src/delegate/delegatevote.h
  src/mpvss/mpvss.cpp
  src/mpvss/mpvss.h
Labels: bug
