Repository bigbangcore/BigBang, pull requests merged in 2020-04, with the labels that each got.

#451 Fix bug
  src/bigbang/rpcmod.cpp
Labels: bug

#449 Improve Unit tests
  .travis.yml
  test/block/block_000001.dat
  test/ctsdb_test.cpp
  test/ipv6_tests.cpp
  test/storage_tests.cpp
Labels: Test

#453 Fix gettransaction bug
  src/bigbang/rpcmod.cpp
Labels: bug

#452 Dpos cert limit
  src/bigbang/base.h
  src/bigbang/blockchain.cpp
  src/bigbang/blockchain.h
  src/bigbang/consensus.cpp
  src/bigbang/error.cpp
  src/bigbang/error.h
  src/bigbang/netchn.cpp
  src/bigbang/schedule.h
  src/bigbang/txpool.cpp
  src/bigbang/txpool.h
Labels: bug

#465 If make DPoS block fail, continue make PoW block
  src/bigbang/blockmaker.cpp
  src/bigbang/blockmaker.h
Labels: bug

#469 Fix vchData verification and DPoS template TX signature bug
  src/bigbang/core.cpp
  src/common/template/delegate.cpp
Labels: bug

#471 Improve the performance of "CStream >> vector"
  src/xengine/stream/stream.h
Labels: Performance

#468 Fix mapSubsribedFork lead to DDOS_ATTACK
  src/bigbang/netchn.cpp
  src/bigbang/netchn.h
Labels: bug

#479 Updating auto lock time of key guard by write-lock instead of read-lock
  src/bigbang/wallet.cpp
  src/bigbang/wallet.h
Labels: bug

#482 Fix cpu console bug
  src/bigbang/rpcclient.cpp
  src/bigbang/rpcclient.h
Labels: bug

#488 Fix Service::GetTxSender Lead to decodetransaction error
  src/bigbang/base.h
  src/bigbang/rpcmod.cpp
  src/bigbang/service.cpp
  src/bigbang/service.h
Labels: bug

#500 Fix RPC::Gettransaction gensis mint tx error
  src/bigbang/service.cpp
Labels: bug

#507 Dpos fix get sender bug
  src/bigbang/service.cpp
Labels: bug

#505 Fix issue 493
  src/bigbang/blockchain.cpp
  src/bigbang/txpool.cpp
  src/storage/blockbase.cpp
  src/storage/blockbase.h
Labels: bug

#514 Fix GetForkBlockView bug
  src/storage/blockbase.cpp
Labels: bug

#520 Update tx fee
  src/bigbang/base.h
  src/bigbang/core.cpp
  src/bigbang/core.h
  src/bigbang/dispatcher.cpp
  src/bigbang/param.h
  src/bigbang/rpcmod.cpp
  src/bigbang/service.cpp
  src/bigbang/struct.h
  src/bigbang/txpool.cpp
  src/bigbang/txpool.h
Labels: enhancement

#448 Add Checkpoints
  src/bigbang/base.h
  src/bigbang/blockchain.cpp
  src/bigbang/blockchain.h
  src/bigbang/netchn.cpp
  src/bigbang/netchn.h
  tools/checkpoints.py
Labels: improvement
