Repository bigbangcore/BigBang, pull requests merged in 2020-08, with the labels that each got.

#579 Support fork checkpoint and Verify vacant block in fork invalid range
  src/bigbang/base.h
  src/bigbang/blockchain.cpp
  src/bigbang/blockchain.h
  src/bigbang/netchn.cpp
Labels: enhancement, improvement

#584 Fork rollback and extended maker
  src/bigbang/base.h
  src/bigbang/blockchain.cpp
  src/bigbang/blockchain.h
  src/bigbang/blockmaker.cpp
  src/bigbang/blockmaker.h
  src/bigbang/checkrepair.cpp
  src/bigbang/checkrepair.h
  src/bigbang/consensus.cpp
  src/bigbang/core.cpp
  src/bigbang/core.h
  src/bigbang/dispatcher.cpp
  src/bigbang/dispatcher.h
  src/bigbang/netchn.cpp
  src/bigbang/param.h
  src/bigbang/rpcmod.cpp
  src/bigbang/schedule.cpp
  src/bigbang/schedule.h
  src/bigbang/txpool.cpp
  src/bigbang/wallet.cpp
  src/bigbang/wallet.h
  src/common/block.h
  src/storage/blockbase.cpp
  src/storage/blockbase.h
Labels: improvement

#588 Add RPC GetTxFee and enhanced transaction arrangeinputs error reporting message
  script/template/rpc.json
  src/bigbang/rpcmod.cpp
  src/bigbang/rpcmod.h
  src/bigbang/service.cpp
  src/bigbang/wallet.cpp
  src/xengine/util.h
  test/CMakeLists.txt
  test/util_tests.cpp
Labels: enhancement

#600 Fix getbalance height bug
  src/bigbang/service.cpp
Labels: bug

#596 Fix mkf CI( storage test, memory leak) and change block's magic number to 0x8F4EBC9E
  src/network/peernet.cpp
  src/storage/timeseries.cpp
  test/block/block_000001.dat
  test/storage_tests.cpp
Labels: bug, enhancement

#602 Fix bug of repeated synchronization due to lack of preamble in POW block
  src/bigbang/netchn.cpp
Labels: bug

#604 Fix fork reference block to submit bug
  src/bigbang/netchn.cpp
  src/bigbang/netchn.h
  src/bigbang/schedule.cpp
  src/bigbang/schedule.h
Labels: bug

#610 Fix security leak of IDataStream
  src/xengine/stream/datastream.h
Labels: bug, security

#612 MakeOirgin for fork defi RPC
  script/template/rpc.json
  src/bigbang/blockchain.h
  src/bigbang/rpcmod.cpp
  src/common/profile.cpp
  src/common/profile.h
  src/jsonrpc/rpc/rpc_type.h
  src/xengine/util.h
  test/util_tests.cpp
Labels: enhancement

#615 Fork defi forkdb
  src/common/forkcontext.h
  src/common/profile.cpp
  src/common/profile.h
  test/util_tests.cpp
Labels: new-feature

#616 Improve DeFi RPC for MakeOrigin
  script/template/rpc.json
  src/bigbang/rpcmod.cpp
Labels: improvement

#617 Add nSupplyCycle for DeFi RPC
  script/template/rpc.json
  src/bigbang/rpcmod.cpp
  src/common/profile.cpp
  src/common/profile.h
  test/util_tests.cpp
Labels: improvement

#621 Fork DeFi blockmaker
  src/bigbang/blockmaker.cpp
  src/bigbang/txpool.cpp
Labels: enhancement

#625 Add DeFi info for listfork RPC
  script/template/rpc.json
  src/bigbang/rpcmod.cpp
Labels: enhancement

#626 Fork defi fix forkcontext
  src/common/forkcontext.h
  src/storage/forkdb.cpp
Labels: enhancement

#628 Add GetAddressInvite RPC for Fork DeFi
  script/template/rpc.json
  src/bigbang/base.h
  src/bigbang/blockchain.cpp
  src/bigbang/blockchain.h
  src/bigbang/rpcmod.cpp
  src/bigbang/rpcmod.h
  src/bigbang/service.cpp
  src/bigbang/service.h
  src/storage/blockbase.cpp
  src/storage/blockbase.h
  src/storage/blockdb.cpp
  src/storage/blockdb.h
Labels: improvement

#629 Add DeFi unit test
  script/template/rpc.json
  src/bigbang/blockchain.cpp
  src/bigbang/blockmaker.cpp
  src/bigbang/core.cpp
  src/bigbang/defi.cpp
  src/bigbang/defi.h
  src/bigbang/param.h
  src/bigbang/rpcmod.cpp
  src/common/profile.h
  test/CMakeLists.txt
  test/defi_test.cpp
Labels: improvement
